# This file was generated by GoReleaser. DO NOT EDIT.
cask "kothaset" do
  name "kothaset"
  desc "High-quality dataset generation CLI for LLM training"
  homepage "https://github.com/shantoislamdev/kothaset"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kothaset"

  on_macos do
    on_intel do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_darwin_amd64.tar.gz"
      sha256 "1ec9483dc144b7462dfbc84ed9ed66fcb88777ff77216be6039f4f99491e1c17"
    end
    on_arm do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_darwin_arm64.tar.gz"
      sha256 "c2fa5267ac46c11cbcf76ff7a001159d919c628ea5f3ee694cbf1fd7eb91a480"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_linux_amd64.tar.gz"
      sha256 "58c83662a96c8b8af1584b309459cae8c87261598d7369d147531d2eec92aac1"
    end
    on_arm do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_linux_arm64.tar.gz"
      sha256 "7cadb364fa662f0425b95db06917a35ebf933c3bbf3977f2afeee5515d8f2178"
    end
  end

  # No zap stanza required
end
