# This file was generated by GoReleaser. DO NOT EDIT.
cask "kothaset" do
  name "kothaset"
  desc "High-quality dataset generation CLI for LLM training"
  homepage "https://github.com/shantoislamdev/kothaset"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kothaset"

  on_macos do
    on_intel do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_darwin_amd64.tar.gz"
      sha256 "5cbda9a688c0e9026397598a4d479737220e0ea7f8bb023837a556264db6244b"
    end
    on_arm do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_darwin_arm64.tar.gz"
      sha256 "ef49c7fedf99998ac21ce1d077f545d6b65d01122dffd41de002cda18cdfc15d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_linux_amd64.tar.gz"
      sha256 "c6c1f0a26b874300ef31fcc77e07ed0c09048ccecb85bd2f3620f76aba7dda0e"
    end
    on_arm do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_linux_arm64.tar.gz"
      sha256 "d9a9d5f99002e9f4a610c9d73e879a388cd26bab5a7c211ea93b0305f4acc948"
    end
  end

  # No zap stanza required
end
