# This file was generated by GoReleaser. DO NOT EDIT.
cask "kothaset" do
  name "kothaset"
  desc "High-quality dataset generation CLI for LLM training"
  homepage "https://github.com/shantoislamdev/kothaset"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kothaset"

  on_macos do
    on_intel do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_darwin_amd64.tar.gz"
      sha256 "cb3fa4e38ab5b5942acd2e44dca74de18d8268948a27a07504a7d117a103d266"
    end
    on_arm do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_darwin_arm64.tar.gz"
      sha256 "1c3c96ebd2683d528eb713ab6e7d992eb0c1143d7ad9cd8910a71af9d995afaa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_linux_amd64.tar.gz"
      sha256 "70d51c5a412d6b8ad61cabc2b4820993927fc0339c98523dcc5c07754c259cf1"
    end
    on_arm do
      url "https://github.com/shantoislamdev/kothaset/releases/download/v#{version}/kothaset_#{version}_linux_arm64.tar.gz"
      sha256 "ea4cf1a4bfcd1f8d7132847ca010a87b59eaec9b96eb2ad7512660b01e27790e"
    end
  end

  # No zap stanza required
end
